services:
  qmk-build:
    build:
      context: .
      dockerfile: Dockerfile.qmk
    container_name: qmk-voyager
    volumes:
      # Mount keymap directory
      - ./qmk_keymaps/muccau:/home/qmk/qmk_firmware/keyboards/zsa/voyager/keymaps/muccau:ro
      # Mount build script
      - ./qmk_keymaps/muccau/_build.sh:/home/qmk/build.sh:ro
      # Mount output directory to get the built firmware
      - ./keybin:/home/qmk/keybin
    working_dir: /home/qmk/qmk_firmware
    command: ["/home/qmk/build.sh"]

  firmware-server:
    image: nginx:alpine
    container_name: qmk-firmware-server
    ports:
      - "8888:8888"
    volumes:
      - ./keybin:/usr/share/nginx/html:ro
      - ./qmk_keymaps/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
